In [3]:
# Numpy : Numerical Python
import numpy as np

In [8]:
one_darray = [1,2,3,4] # List of array
print(type(one_darray))

<class 'list'>


In [6]:
numpy_one_darray = np.array(one_darray) # converting list into numpy array
print(type(numpy_one_darray)) # type of numpyarray

<class 'numpy.ndarray'>


In [7]:
print(numpy_one_darray.ndim) # shows dimensions
print(numpy_one_darray.shape) # shows the shape of the numpyarray

1
(4,)


In [10]:
numpy_two_darray = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(numpy_two_darray.ndim)
print(numpy_two_darray.shape)
numpy_two_darray

2
(2, 5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
numpy_three_darray = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(type(numpy_three_darray))
print(numpy_three_darray.ndim)
print(numpy_three_darray.shape)
numpy_three_darray

<class 'numpy.ndarray'>
3
(1, 3, 3)


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [12]:
np.ones(6,dtype = int)

array([1, 1, 1, 1, 1, 1])

In [14]:
np.ones((3,3),dtype = int) # identity matrix

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
np.zeros(5, dtype = int)

array([0, 0, 0, 0, 0])

In [29]:
np.zeros((3,3), dtype = int) # we change it to INTEGER because the by default datatype is FLOAT

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
a = np.array([[2,2],[4,2]])
b = np.array([[4,4],[2,2]])
answer_two_darray = a * b
print(answer_two_darray)

[[8 8]
 [8 4]]


In [32]:
b.transpose()
print(answer_two_darray.transpose)
# numpy is vectorized form of array built on the top of the list which fastens the computational operations

<built-in method transpose of numpy.ndarray object at 0x00000256C742C810>


In [34]:
# ARRANGE
num = np.arange(1,100)
print(num)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [39]:
#linspace
num1 = np.linspace(1,100,2, dtype = int)
print(num1)

[  1 100]
